<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>article_media</name>
   <tag></tag>
   <elementGuidId>d4198f4d-5e0c-48bf-825e-6a879b6ad2c2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>article</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main main no-padding-bottom bg-grey saldo&quot;]/div[2]/div[2]/section[@class=&quot;section is-paddingless has-shadow undefined&quot;]/div[@class=&quot;seller-akun&quot;]/div[@class=&quot;profile-wrapp undefined&quot;]/ul[1]/li[1]/div[@class=&quot;box is-paddingless&quot;]/article[@class=&quot;media&quot;]</value>
   </webElementProperties>
</WebElementEntity>
