<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_icon-arrow-right</name>
   <tag></tag>
   <elementGuidId>690b00d2-6ef5-4c62-a4f4-9025a670400b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main main no-padding-bottom bg-grey saldo&quot;]/div[1]/div[2]/div[1]/section[@class=&quot;section is-paddingless has-shadow xs-margin-top&quot;]/div[@class=&quot;payment-detail saldo-history&quot;]/ul[1]/li[1]/div[@class=&quot;columns is-mobile is-multiline no-margin-bottom&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;is-left has-text-right&quot;]/span[@class=&quot;icon-arrow-right&quot;]</value>
   </webElementProperties>
</WebElementEntity>
