<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Mandiri</name>
   <tag></tag>
   <elementGuidId>c7eba7dd-bb08-4f83-b190-6aeffb33fc8b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mandiri</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[1]/div[2]/div[@class=&quot;main main no-padding-bottom bg-white saldo&quot;]/div[2]/section[@class=&quot;section is-paddingless&quot;]/div[@class=&quot;sort-option sortButton&quot;]/div[@class=&quot;sort-list sortButton&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;control popup-option change-address&quot;]/label[@class=&quot;radio undefined&quot;]/strong[1]</value>
   </webElementProperties>
</WebElementEntity>
